---
output: github_document
---

```{r setup}
library(tidyverse)
library(adaptivetau)
```




```{r}
dem_rates <- function(s, p, t) {
  x <- s[["x"]] / p$N
  y <- s[["y"]] / p$N
  
  c(p$bx * x * (1 - x - y),     # x birth rate
    p$dx * x,                   # x death rate
    p$c * x * y,                # competition
    p$by * y * (1 - x - y),     # y birth rate
    p$dy * y                    # y death rate
  )
}


env_rates <- function(s, p, t) {
  
  x <- s[["x"]] / p$N
  y <- s[["y"]] / p$N
  
  c(p$bx * x * max(1 - x - y, 0), # x birth rate
    p$dx * x,                                 # x death rate
    p$c * x * y, # competition
    p$by * y * max(1/2 - y, 0), # y birth rate
    p$dy * y                               # y death rate
  )
}

```


```{r}
dem_transitions  = list(c(x = +1), # x colonizes new patch
                   c(x = -1), # x death event
                   c(x =  +1, y = -1), # a two-step process, x replaces y
                   c(y = +1), # y colonizes a new patch
                   c(y = -1) # y death event
                   )

# indicate state variable and the change
env_transitions = list(c(x = +1), # x colonizes new patch
                   c(x = -1), # x death event
                   c(x =  0, y = 0), # a two-step process, x replaces y
                   c(y = +1), # y colonizes a new patch
                   c(y = -1) # y death event
                   )


```



```{r}
N <- 100
params <- list(bx = 0.2, by = 0.5, dx = 0.1,dy = 0.1, c=0.1, N=N)
inits = c(x = 20, y = 20)

```

```{r}
set.seed(1234) # set random number generator seed to be reproducible
sim <- 
  adaptivetau::ssa.exact(c(x = 20, y = 0),
                       env_transitions, 
                       env_rates,
                       params,
                       tf=2e4) 
```

```{r}
sim %>% 
  as_tibble() %>%
  sample_n(1e3) %>% ## avoid plotting too many points
  gather(species, population, -time) %>% 
 ggplot(aes(time, population, col = species)) + geom_line()
```




```{r}
set.seed(1234) # set random number generator seed to be reproducible
sim2 <- 
  adaptivetau::ssa.exact(inits,
                       env_transitions, 
                       env_rates,
                       params,
                       tf=2e4) 
```

```{r}
sim2 %>% 
  as_tibble() %>%
  sample_n(1e3) %>% ## avoid plotting too many points
  gather(species, population, -time) %>% 
 ggplot(aes(time, population, col = species)) + geom_line()
```



```{r}
set.seed(1234) # set random number generator seed to be reproducible
sim3 <- 
  adaptivetau::ssa.exact(inits,
                       dem_transitions, 
                       dem_rates,
                       params,
                       tf=2e4) 
```

```{r}
sim3 %>% 
  as_tibble() %>%
  sample_n(1e3) %>% ## avoid plotting too many points
  gather(species, population, -time) %>% 
 ggplot(aes(time, population, col = species)) + geom_line()
```


We can express the variance observed in species `x` in terms of the contribution from 

```{r}
pop <- params$N
crowley_parameters <- c(b1=params$bx, b2=params$by, 
							d1=params$dx, d2=params$dy, c1=params$c, 
							c2=params$c, K=params$N)

	times <- seq(0,200,length=50)
	Xo <- inits
	#ibm <- crowley_ibm(Xo = Xo, parameters=crowley_parameters, times=times,reps=20)

	crowley_sim <- linear_noise_approx(
				inits, times, crowley_parameters, 
				b_crowley, d_crowley, J_crowley,
				T_crowley, Omega=pop)

	colnames(crowley_sim) <- c("time", "x", "y", "var_x", "var_y", "cov")
	crowley_sim <- as_tibble(crowley_sim)
	
```

```{r}
crowley_sim %>% ggplot(aes(time)) + 
  geom_ribbon(aes(y = x, ymin = x - sqrt(var_x), ymax = x + sqrt(var_x), fill="x"), alpha = 0.5) +
  geom_line(aes(y = x, col = "x")) + 
  geom_ribbon(aes(y = y, ymin = y - sqrt(var_y), ymax = y + sqrt(var_y), fill="y"), alpha = 0.5) +
  geom_line(aes(y =y, col="y")) + 
  geom_line(aes(time, population, col = species), data = sim3)
```

```{r}
crowley_sim %>% select(-cov) %>% 
gather(variable, value, -time) %>% ggplot(aes(time, value, col=variable)) + geom_line()
```




```{r}
## Equivalent matrix format
transitions = matrix(c( 1,  0, # x colonizes new patch
                       -1,  0, # x death event
                        1, -1, # a two-step process, x replaces y
                        0,  1, # y colonizes a new patch
                        0, -1 #  y death event
                   ), nrow = 2)

```

